-----------------------------------------------------
-- CONFIGURATION UI
-----------------------------------------------------
-- Reports Tab
-----------------------------------------------------

-----------------------------------------------------
-- Namespaces
-----------------------------------------------------
local _, core = ...;

core.options.args.reportsGroup = {
    order = 3,
    type = "group",
    name = "Reports",
    args = {
        -- Interrupts Reporting
        interruptsHeader = {
            order = 0,
            type = "header",
            name = "Interrupts Reporting",
        },
        interruptsPaddingTop = {
            order = 1,
            type = "description",
            fontSize = "large",
            name = " ",
        },
        topInterruptsToggle = {
            order = 2,
            type = "toggle",
            name = "Report Top Interrupts",
            desc = "Report the highest amount of interrupts",
            descStyle = "inline",
            width = "full",
            get = function() return core.db.profile.reportConfig["INTERRUPTS"]["TOP"] end,
            set = function(info, value) core.db.profile.reportConfig["INTERRUPTS"]["TOP"] = value end,
        },
        bottomInterruptsToggle = {
            order = 3,
            type = "toggle",
            name = "Report Bottom Interrupts",
            desc = "Report the lowest amount of interrupts",
            descStyle = "inline",
            width = "full",
            get = function() return core.db.profile.reportConfig["INTERRUPTS"]["BOTTOM"] end,
            set = function(info, value) core.db.profile.reportConfig["INTERRUPTS"]["BOTTOM"] = value end,
        },
        combatInterruptsToggle = {
            order = 4,
            type = "toggle",
            name = "Report After Combat",
            desc = "Report interrupts after all combat segments",
            descStyle = "inline",
            width = "full",
            get = function() return core.db.profile.reportConfig["INTERRUPTS"]["COMBAT"] end,
            set = function(info, value) core.db.profile.reportConfig["INTERRUPTS"]["COMBAT"] = value end,
        },
        bossInterruptsToggle = {
            order = 5,
            type = "toggle",
            name = "Report After Bosses",
            desc = "Report interrupts after bosses",
            descStyle = "inline",
            width = "full",
            get = function() return core.db.profile.reportConfig["INTERRUPTS"]["BOSS"] end,
            set = function(info, value) core.db.profile.reportConfig["INTERRUPTS"]["BOSS"] = value end,
        },
        dungeonInterruptsToggle = {
            order = 6,
            type = "toggle",
            name = "Report After M+ Dungeons",
            desc = "Report interrupts after M+ completion",
            descStyle = "inline",
            width = "full",
            get = function() return core.db.profile.reportConfig["INTERRUPTS"]["DUNGEON"] end,
            set = function(info, value) core.db.profile.reportConfig["INTERRUPTS"]["DUNGEON"] = value end,
        },
        interruptsPaddingBottom = {
            order = 7,
            type = "description",
            fontSize = "large",
            name = " ",
        },

        -- Damage Reporting
        damageHeader = {
            order = 8,
            type = "header",
            name = "Damage Dealt (DPS) Reporting (Details! required)",
        },
        damagePaddingTop = {
            order = 9,
            type = "description",
            fontSize = "large",
            name = " ",
        },
        topDamageToggle = {
            order = 10,
            type = "toggle",
            name = "Report Top Damage",
            desc = "Report the highest damage dealt",
            descStyle = "inline",
            width = "full",
            get = function() return core.db.profile.reportConfig["DAMAGE"]["TOP"] end,
            set = function(info, value) core.db.profile.reportConfig["DAMAGE"]["TOP"] = value end,
            disabled = function() return NemesisChatAPI:GetAPI("NC_DETAILS"):IsEnabled() == false or not Details end,
        },
        bottomDamageToggle = {
            order = 11,
            type = "toggle",
            name = "Report Bottom Damage",
            desc = "Report the lowest damage dealt",
            descStyle = "inline",
            width = "full",
            get = function() return core.db.profile.reportConfig["DAMAGE"]["BOTTOM"] end,
            set = function(info, value) core.db.profile.reportConfig["DAMAGE"]["BOTTOM"] = value end,
            disabled = function() return NemesisChatAPI:GetAPI("NC_DETAILS"):IsEnabled() == false or not Details end,
        },
        combatDmgToggle = {
            order = 12,
            type = "toggle",
            name = "Report After Combat",
            desc = "Report damage after all combat segments",
            descStyle = "inline",
            width = "full",
            get = function() return core.db.profile.reportConfig["DAMAGE"]["COMBAT"] end,
            set = function(info, value) core.db.profile.reportConfig["DAMAGE"]["COMBAT"] = value end,
            disabled = function() return NemesisChatAPI:GetAPI("NC_DETAILS"):IsEnabled() == false or not Details end,
        },
        bossDmgToggle = {
            order = 13,
            type = "toggle",
            name = "Report After Bosses",
            desc = "Report damage after bosses",
            descStyle = "inline",
            width = "full",
            get = function() return core.db.profile.reportConfig["DAMAGE"]["BOSS"] end,
            set = function(info, value) core.db.profile.reportConfig["DAMAGE"]["BOSS"] = value end,
            disabled = function() return NemesisChatAPI:GetAPI("NC_DETAILS"):IsEnabled() == false or not Details end,
        },
        dungeonDmgToggle = {
            order = 14,
            type = "toggle",
            name = "Report After M+ Dungeons",
            desc = "Report damage after M+ completion",
            descStyle = "inline",
            width = "full",
            get = function() return core.db.profile.reportConfig["DAMAGE"]["DUNGEON"] end,
            set = function(info, value) core.db.profile.reportConfig["DAMAGE"]["DUNGEON"] = value end,
            disabled = function() return NemesisChatAPI:GetAPI("NC_DETAILS"):IsEnabled() == false or not Details end,
        },
        damagePaddingBottom = {
            order = 15,
            type = "description",
            fontSize = "large",
            name = " ",
        },

        -- Avoidable Damage Reporting
        adHeader = {
            order = 16,
            type = "header",
            name = "Avoidable Damage Taken Reporting (GTFO required)",
        },
        adPaddingTop = {
            order = 17,
            type = "description",
            fontSize = "large",
            name = " ",
        },
        topAdToggle = {
            order = 18,
            type = "toggle",
            name = "Report Top Avoidable Damage Taken",
            desc = "Report the highest amount of avoidable damage taken",
            descStyle = "inline",
            width = "full",
            get = function() return core.db.profile.reportConfig["AVOIDABLE"]["TOP"] end,
            set = function(info, value) core.db.profile.reportConfig["AVOIDABLE"]["TOP"] = value end,
            disabled = function() return NemesisChatAPI:GetAPI("NC_GTFO"):IsEnabled() == false or not GTFO end,
        },
        bottomAdToggle = {
            order = 19,
            type = "toggle",
            name = "Report Bottom Avoidable Damage Taken",
            desc = "Report the lowest amount of avoidable damage taken",
            descStyle = "inline",
            width = "full",
            get = function() return core.db.profile.reportConfig["AVOIDABLE"]["BOTTOM"] end,
            set = function(info, value) core.db.profile.reportConfig["AVOIDABLE"]["BOTTOM"] = value end,
            disabled = function() return NemesisChatAPI:GetAPI("NC_GTFO"):IsEnabled() == false or not GTFO end,
        },
        combatAdToggle = {
            order = 20,
            type = "toggle",
            name = "Report After Combat",
            desc = "Report avoidable damage after all combat segments",
            descStyle = "inline",
            width = "full",
            get = function() return core.db.profile.reportConfig["AVOIDABLE"]["COMBAT"] end,
            set = function(info, value) core.db.profile.reportConfig["AVOIDABLE"]["COMBAT"] = value end,
            disabled = function() return NemesisChatAPI:GetAPI("NC_GTFO"):IsEnabled() == false or not GTFO end,
        },
        bossAdToggle = {
            order = 21,
            type = "toggle",
            name = "Report After Bosses",
            desc = "Report avoidable damage after bosses",
            descStyle = "inline",
            width = "full",
            get = function() return core.db.profile.reportConfig["AVOIDABLE"]["BOSS"] end,
            set = function(info, value) core.db.profile.reportConfig["AVOIDABLE"]["BOSS"] = value end,
            disabled = function() return NemesisChatAPI:GetAPI("NC_GTFO"):IsEnabled() == false or not GTFO end,
        },
        dungeonAdToggle = {
            order = 22,
            type = "toggle",
            name = "Report After M+ Dungeons",
            desc = "Report avoidable damage after M+ completion",
            descStyle = "inline",
            width = "full",
            get = function() return core.db.profile.reportConfig["AVOIDABLE"]["DUNGEON"] end,
            set = function(info, value) core.db.profile.reportConfig["AVOIDABLE"]["DUNGEON"] = value end,
            disabled = function() return NemesisChatAPI:GetAPI("NC_GTFO"):IsEnabled() == false or not GTFO end,
        },
        adPaddingBottom = {
            order = 23,
            type = "description",
            fontSize = "large",
            name = " ",
        },
    },
}